export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  GENERAL_DIRECTOR = 'GENERAL_DIRECTOR',
  OPERATION_DIRECTOR = 'OPERATION_DIRECTOR',
  TECHNICAL_DIRECTOR = 'TECHNICAL_DIRECTOR',
  CHIEF_ACCOUNTANT = 'CHIEF_ACCOUNTANT',
  EXPERT = 'EXPERT',
  ENGINEER = 'ENGINEER',
  ASSISTANT = 'ASSISTANT',
  FREELANCER = 'FREELANCER',
}
