export enum ActionLogActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  UPLOAD_FILE = 'UPLOAD_FILE',
  UPDATE_FILE = 'UPDATE_FILE',
  DELETE_FILE = 'DELETE_FILE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  AI_ACTION = 'AI_ACTION',
  SYNC_PULL = 'SYNC_PULL',
  SYNC_PUSH = 'SYNC_PUSH',
}
